name: Flutter CI - Build Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Android APK and AAB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android NDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '27.0.12077973'

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'
          cache: true

      - name: Verify Flutter and Dart Versions
        run: |
          flutter --version
          dart --version

      - name: Clean Project
        run: |
          flutter clean
          flutter pub get

      - name: Build Android
        run: |
          flutter build apk --release
          flutter build appbundle --release
        working-directory: ./

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/bundle/release/*.aab
          retention-days: 7